LUGAT = {
    ("homo", "inis", "m", "ot") : "odam",
    ("vesica", "ae", "f", "ot") : "pufak",
    ("fundus", "i", "m", "ot") : "tub",
    ("dorsum", "i", "n", "ot") : "orqa",
    ("auris","is","f","ot") : "quloq",
    ("bronchus","i","m","ot") : "Bronx",
    ("coccyx","this","m","ot") : "quyruq, dum",
    ("cerebrum","i","m","ot") : "katta miya",
    ("dens","dentis","m","ot") : "tish",
    ("ethmoidalis","e","sifat") : "g'alvirsimon",
    ("flos","floris","m","ot") : "gul", 
    ("gaster","tris","f","ot") : "oshqozon, me'da", 
    ("humerus","i","m","ot") : "yelka suyagi", 
    ("ileum","i","n","ot") : "ichak", 
    ("jejunum","i","n","ot") : "ingichka, ichak", 
    ("labium","ii","n","ot") : "lab",
    ("musculus","i","m","ot") : "mushak,muskul", 
    ("nasus","i","m","ot") : "burun", 
    ("orbita","ae","f","ot") : "ko'z kosasi", 
    ("patella","ae","f","ot") : "tizza qopqog'i", 
    ("quadratus","a","um","ot") : "kvadrat", 
    ("ren","renis","m","ot") : "buyrak", 
    ("scapula","ae","f","ot") : "kurak", 
    ("thorax","acis","m","ot") : "ko'krak",
    ("unguis","is","m","ot") : "tirnoq", 
    ("vertebra","ae","f","ot") : "umurtqa", 
    ("larynx","yngis","m","ot") : "hiqildoq", 
    ("hyoideus","a","um","ot") : "til osti",
    ("zygoma","atis","n","ot") : "yonoq, bet suyagi",
    ("keras","atos","ot") : "ko'z shox pardasi"
}
