LUGAT = {   
    ("homo", "inis", "m", "ot") : "odam",
    ("vesica", "ae", "f", "ot") : "pufak",
    ("fundus", "i", "m", "ot") : "tub",
    ("dorsum", "i", "n", "ot") : "orqa",
    ("auris","is","f","ot") : "quloq",
    ("bronchus","i","m","ot") : "bronx",
    ("coccyx","this","m","ot") : ("quyruq", "dum"),
    ("cerebrum","i","m","ot") : "katta miya",
    ("dens","dentis","m","ot") : "tish",
    ("ethmoidalis","e","sifat") : "g'alvirsimon",
    ("flos","floris","m","ot") : "gul", 
    ("gaster","tris","f","ot") : ("oshqozon", "me'da"), 
    ("humerus","i","m","ot") : "yelka suyagi", 
    ("ileum","i","n","ot") : "ichak", 
    ("jejunum","i","n","ot") : "ingichka ichak", 
    ("labium","ii","n","ot") : "lab",
    ("musculus","i","m","ot") : ("mushak", "muskul"), 
    ("nasus","i","m","ot") : "burun", 
    ("orbita","ae","f","ot") : "ko'z kosasi", 
    ("patella","ae","f","ot") : "tizza qopqog'i", 
    ("quadratus","a","um","ot") : "kvadrat", 
    ("ren","renis","m","ot") : "buyrak", 
    ("scapula","ae","f","ot") : "kurak", 
    ("thorax","acis","m","ot") : "ko'krak",
    ("unguis","is","m","ot") : "tirnoq", 
    ("vertebra","ae","f","ot") : "umurtqa", 
    ("larynx","yngis","m","ot") : "hiqildoq", 
    ("hyoideus","a","um","ot") : "til osti",
    ("zygoma","atis","n","ot") : ("yonoq", "bet suyagi"),
    ("keras","atos","ot") : "ko'z shox pardasi",
    ("vertebra","ae","f","ot") : "umurtqa",
    ("cranium","i","n","ot"):"kalla suyagi",
    ("pectus","oris","n","ot"):"ko'krak",
    ("palma","aris","m","ot"):"kaft",
    ("fibula","ae","f","ot"):"kichik boldir suyagi",
    ("tibia","ae","f","ot"):"katta boldir suyagi",
    ("planta","ae","f","ot"):"oyoq tagi",
    ("nasus","i","m","ot"):" burun",
    ("costa","ae","f","ot"):"qovurg'a",
    ("dorsum","i","m","ot"):"orqa",
    ("femor","oris","n","ot"):"son suyagi",
    ("pulmo","onis","m","ot"):"o'pka",
    ("cerebrum","i","n","ot"):"katta miya",
    ("arcus","us","m","ot"):"yoy",
    ("cornu","us","n","ot"):"shox",
    ("processus","us","m","ot"):"o'simta",
    ("genu","us","n","ot"):"tizza",
    ("manus","us","f","ot"):"qo'l panjasi",
    ("facies","ei","f","ot"):"yuza",
    ("superficies","ei","f","ot"):"yuza",
    ("auditus","us","m","ot"):"eshituv",
    ("incus","udus","f","ot"):"sandom",
    ("visus","us","m","ot"):"ko'rish",
    ("senectus","utis","f","ot"):"qarilik",
    ("esophagus","i","m","ot"):"qizilo'ngach",
    ("ulcus","eris","n","ot"):"yara",
    ("processus","us","m","ot"):"o'simta",
    ("viscus","eris","n","ot"):"ichki a'zo",
    ("abscessus","us","m","ot"):"yorilishi",
    ("aditus","us","m","ot"):"kirish",
    ("exitus","us","m","ot"):"natija",
    ("casus","us","m","ot"):"voqea",
    ("habitus","us","m","ot"):"tashqi ko'rinish",
    ("hiatus","us","m","ot"):("yoriq","teshik"),
    ("pulsus","us","m","ot"):"puls",
    ("usus","us","m","ot"):"qo'llanish",
    ("collapsus","us","m","ot"):"yurakning o'tkir yetishmovchiligi",
    ("istus","us","m","ot"):("itarish","turtish"),
    ("caries","ei","f","ot"):"chirishlik",
    ("scabies","ei","f","ot"):"qo'tir",
    ("rabies","ai","f","ot"):"qutirish",
    ("species","ei","f","ot"):("yig'ma","to'plam"),
    ("acidum","i","n","ot"):"kislota",
    ("achillea","ae","f","ot"):"bo'ymadron", 
    ("acorus(i) colamus(i)","ot"):"oddiy igir", 
    ("acyclidinum","i","n","ot"):"atsiklidin", 
    ("adeps","ipis","m","ot"):"yog'", 
    ("addo","ere","3","fe'l"):"qo'shmoq", 
    ("adonis","idis","m","ot"):"adonis(gulizardak, safsargul)", 
    ("adonis(idis) vernalis(is)","ravish"):"bahorgi", 
    ("aethacridinum","i","n","ot"):"etakridin", 
    ("aethamidum","i","n","ot"):"etamid", 
    ("aethimizolum","i","n","ot"):"etimizol", 
    ("aethinyloestradiolum","i","n","ot"):"etinilestradiyol",
    ("aether","eris","m","ot"):"efir", 
    ("aethereus","a","um","ot"):"efir(moyli)li", 
    ("aethylicus","a","um","ot"):"etil(spirti)li", 
    ("aethylium","i","n","ot"):"etil", 
    ("alcaloidum","i","n","ot"):"yomtoq", 
    ("allium(i) sativum(i)"):"sarimsoq piyoz", 
    (" allocholum","i","n","ot"):"alloxol", 
    ("alnus","i","f","ot"):"qandag'och, olxa", 
    ("althaea","ea","f"):"gulxayri", 
    ("amidopyrinum","i","n","ot"):"amidopirin", 
    ("aminalonum","i","n","ot"):"aminalon", 
    ("aminalonum","i","n","ot"):"aminazin",
    ("ammoniates","a","um","sifat"):"ammiakli", 
    ("ampulla","ar","f","ot"):"ampula",
    ("amygdala","ar","f","ot"):"bodom", 
    ("amylaceus","a","um","sifat"):"kraxmalli", 
    ("amylum","I","n","ot"):"kraxmal", 
    ("ana"):"teng, teng miqdorda", 
    ("anaesthesinum","i","n","ot"):"anestezin", 
    ("anaesthetics","a","um"):"og'riqsizlantiruvchi", 
    ("anabasis","ahpylla","ot"):"maymunjon", 
    ("anethum","i","n","ot"):"shivit", 
    ("anisum","i","n","ot"):"arpabodiyon, oddiy Anis", 
    ("antiasthmaticus","a","um","ot"):"ich ketishiga qarshi", 
    ("aloё","ё","f"):"alloy",
    ("antidotum","i","n","ot"):"zaharga qarshi dori", 
    ("antigangraenosus","a","um","ot"):"gangrenaga qarshi", 
    ("antihaemorrhoidalis","e","ot"):"bevoailga qarshi", 
    ("antipestosus","a","um","ot"):"o'latga qarshi", 
    ("antipyreticus","a","um","ot"):"issiqni pasaytiruvchi", 
    ("antirabicus","a","um","ot"):"quturushga qarshi", 
    ("antisepticus","a","um","ot"):"antiseptik", 
    ("antitetanicus","a","um","ot"):"qoqsholga qarshi",
    ("apomorphinum","i","n","ot"):"apomorfin", 
    ("aprenalum","i","n","ot"):"aprenol", 
    ("apressinum","i","n","ot"):"apressin", 
    ("aprophenum","i","n","ot"):"apofen", 
    ("arctium","i","n","sifat"):"qariqiz", 
    ("arachis","idis","f","ot"):"yeryong'oq", 
    ("aralia","ae","f","ot"):"araliya",
    ("argentum","i","n","ot"):"kumush", 
    ("armeniaca","ae","f","ot"):"o'rik", 
    ("aromaticus","a","um","ot"):"xushbo'y", 
    ("arsenicum","i","n","ot"):"margumush",
    ("aurum","i","n","ot"):"oltin", 
    ("audio","ire","4","fe'l"):"eshitmoq",
    ('chole','es',"f","ot"):"o't",
    ("ala","ae","f","ot"):"qanot",
    ("aorta","ae","f","ot"):"aorta", 
    ("arteria","ae","f","ot"):"arteriya", 
    ("concha","ae","f","ot"):"chig'anoq", 
    ("costa","ae","f","ot"):"qovurg'a", 
    ("orbita","ae","f","ot"):"ko'z kosasi", 
    ("scapula","ae","f","ot"):"kurak", 
    ("spina","ae","f","ot"):"o'tkir qirra", 
    ("vena","ae","f","ot"):"vena", 
    ("crista","ae","f","ot"):"qirra", 
    ("lamina","ae","f","ot"):"plastinka", 
    ("lingua","ae","f","ot"):"til", 
    ("mandibula","ae","f","ot"):"pastki jag'", 
    ("maxilla","ae","f","ot"):"yuqori jag'", 
    ("patella","ae","f","ot"):"tizza qopqog'i", 
    ("sutura","ae","f","ot"):"chok", 
    ("tuba","ae","f","ot"):"nay", 
    ("vertebra","ae","f","ot"):"umurtqa",
    ("clavicula","ae","f","ot"):("o'mrov","o'mrov suyagi"),
    ("fascia","ae","f","ot"):"mushakni o'rab turuvchi yupqa parda",
    ("nucha","ae","f","ot"):"ensa",
    ("tibia","ae","f","ot"):"katta boldir suyagi",
    ("tonsilla","ae","ot"):"bodomcha",
    ("fibula","ae","f","ot"):"kichik boldir suyagi",
    ("squama","ae","f","ot"):"tangacha",
    ("ulna","ae","f","ot"):"tirsak suyagi",
    ("nasus","i","m","ot"):"burun",
    ("vestibulum","i","n","ot"):"dahliz",
    ("porus","i","m","ot"):"teshik",
    ("palatum","i","n","ot"):"tanglay",
    ("organum","i","n","ot") : ( "organ", "a'zo"),
    ("caput","itis","n","ot"):"bosh",
    ("os","oris","n","ot"):"og'iz",
    ("pterygoideus","a","um","sifat"):"qanotsimon",
    ("venosus","a","um","sifat"):"veno qon tomiriga oid",
    ("asper","a","um","sifat"):"g'adir-budur",
    ("iliacus","a","um","sifat"):("yonbosh","ichakka","oid"),
    ("niger","gra","grum","sifat"):"qora",
    ("thyr(e)","oideus","a","um","sifat"):"qalqonsimon",
    ("albus","a","um","sifat"):"oq",
    ("coronarius","a","um","sifat"):"tojsimon",
    ("liber","era","erum","sifat"):("erkin","ozod"),
    ("sacer","cra","crum","sifat"):"dumg'azaga oid",
    ("durus","a","um","sifat"):"qattiq",
    ("mylohyoideus","a","um","sifat"):"jag' til ostiga tegishli",
    ("massetericus","a","um","sifat"):"chaynovga oid",
    ("palatoglossus","a","um","sifat"):("tanglay","tilga oid"),
    ("alaris","e","sifat"):("qanotga","oid"),
    ("cervicalis","e","sifat"):"bo'yinga oid",
    ("frontalis","e","sifat"):"peshonaga oid",
    ("mandibularis","e","sifat"):"pastki jag'ga oid",
    ("occipitalis","e","sifat"):"ensaga oid",
    ("sphenoidalis","e","sifat"):"ponasimon",
    ("vertebralis","e","sifat"):"umurtqaga oid",
    ("sacralis","e","sifat"):"dumg'azaga oid",
    ("cerebralis","e","sifat"):"miyaga oid",
    ("ethmoidalis","e","sifat"):"g'alvirsimon",
    ("maxillaris","e","sifat"):"yuqori jag'ga oid",
    ("nasalis","e","sifat"):"burunga oid",
    ("orbitalis","e","sifat"):"ko'z kosasiga oid",
    ("temporalis","e","sifat"):"chakkaga oid",
    ("jugularis","e","sifat"):"bo'yinturuq",
    ("alveolaris","e","sifat"):("alveolangan","katakli","pufakli"),
    ("dentalis","e","sifat"):"tishga oid",
    ("mentalis","e","sifat"):"engakka oid",
    ("buccalis","e","sifat"):"lunju",
    ("infraorbitalis","e","sifat"):"ko'z kosasi ostiga oid",
    ("mollis","e","sifat"):"yumshoq",
}
